
spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: configserver:http://localhost:5005
  cloud:
    config:
      enabled: true
      name: application
      profile: dev
      label: master
server:
  port: 5002

