
spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: configserver:https://api-cloud-config.herokuapp.com
  cloud:
    config:
      enabled: true
      name: application
      profile: dev
      label: master
server:
  port: 5002

